/* api/leveldb/leveldb_terark_config.h.  Generated from config.hin by configure.  */
/* api/leveldb/config.hin.  Generated by autoheader, then hand-edited. */

/* Build the LevelDB API with Basho LevelDB support. */
/* #undef HAVE_BASHOLEVELDB */

/* Snappy support automatically loaded. */
/* #undef HAVE_BUILTIN_EXTENSION_SNAPPY */

/* Zlib support automatically loaded. */
/* #undef HAVE_BUILTIN_EXTENSION_ZLIB */

/* Define to 1 for diagnostic tests. */
/* #undef HAVE_DIAGNOSTIC */

/* Build the LevelDB API with HyperLevelDB support. */
/* #undef HAVE_HYPERLEVELDB */

/* Define to 1 if you have the `snappy' library (-lsnappy). */
//#define HAVE_LIBSNAPPY 1

/* Build the LevelDB API with RocksDB support. */
//#define HAVE_ROCKSDB 1
